### ISSUE TITLE
New optional action argument for nxos_switchport

### ISSUE THREAD

**Issue by jonasstenling** [jedelman8/nxos-ansible#25]
A common standard task in a Nexus network is to add or remove a VLAN from a VLAN trunk. With the current nxos_switchport module it's only possible to assign one or many VLANs on a trunk, but there is no way to add or remove VLANs without specifying all VLANs that shall be permitted on the trunk.

I suggest to add a new optional `action` argument for the nxos_switchport module.

`action = add`
The `trunk_vlans` parameter will be used as the source of all VLANs to add to the trunk.

`action = remove`
The `trunk_vlans` parameter will be used as the source of all VLANs to remove from the trunk.

`action = None`
The `trunk_vlans` parameter will be used as the definitive source of all VLANs to be permitted on the trunk. This is the current behaviour.

**Comment by jedelman8** [comment]
Thanks for the suggestion.  First off, many of these modules should be cleaned up, but that's not technically your problem :).  Second, I like the idea of being able to add/remove VLANs from the trunk, so great idea.

The current module supports `state=absent` and `state=present`.  `state=absent` just defaults the config on that switchport.  How about making a new option for the `state` parameter?  We can use `state=default` to default the switchport config (still keep the checks to ensure it is in fact an L2 port, etc.).

But when `trunk_vlans` is set and `state=present`, it'll work as normal.  When set to `state=absent`, it'll remove the VLANs from the trunk.

The grey area comes in when thinking about `native_vlan` and `access_vlan` along with the state parameter.  With using Ansible methods such as `required_together`, `mutually_exlcusive`, and `required_one_of`, we should be able to do it though.  

`mutually_exclusive` should definitely be used with trunk_vlans and access_vlan.  So, when `state=absent` and `access_vlan` is set, just ensure that VLAN is not the access vlan, in effect, doing `no switchport access vlan 10`, as an example.  As for `native_vlan`, we can just disregard it when `state=absent`.  If it ever needs to be changed, `state=present` can continue to be used and of course, `state=default` could now be used for default the full switchport config if it's a L2 port.  Otherwise, use `state=default` within the interface module.

What do you think?

**Comment by jonasstenling** [comment]
Well, that sounds reasonable, but how does a new `action` parameter fit in to that picture? :-)

**Comment by jedelman8** [comment]
It doesn't... :)

Trying to minimize the amount of change and params with accomplishing the
goal :)

**Comment by jonasstenling** [comment]
Well, then I'm confused.
Do you mean when `state=present` then add vlans in `trunk_vlans` to the trunk?

**Comment by jedelman8** [comment]
Yes, that's correct.  That was implicit in my description...state=present wouldn't change for anything...only thing changing are state=absent/default options.

That help?

**Comment by jonasstenling** [comment]
How would it be possible to remove selected vlans from the trunk with your suggested solution?

**Comment by jedelman8** [comment]
From above:

But when trunk_vlans is set and state=present, it'll work as normal. When set to state=absent, it'll remove the VLANs from the trunk. :)

**Comment by jedelman8** [comment]
If you are going to tackle this, it may be good to start with a detailed docstring for the modifed Ansible module and the `AnsibleModule` object within the module so we can see/agree on all  parameters and uses, etc.  Issue a PR on that, we can review docs and object, then start the dev process...let me know what you think.

**Comment by jonasstenling** [comment]
Agreed, I will do so and do a PR when I'm done.

One final question. With `state=present` it would only add the vlans in `trunk_vlans` and leave any existing vlans in the trunk untouched?

**Comment by jonasstenling** [comment]
PR https://github.com/jedelman8/nxos-ansible/pull/28 created.

**Comment by jonasstenling** [comment]
This issue has been resolved in the refactored nxos_switchport.py module in the modules-no-pycsco-utils branch.
